sonar.projectKey=ipsita-17_enterprise-ai-aks-inference-platform
sonar.organization=ipsita-17

sonar.sources=api,model,scripts

sonar.tests=api/tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=\
**/__pycache__/**,\
**/*.pyc

sonar.coverage.exclusions=\
model/training/train.py,\
model/training/mlflow_config.py,\
scripts/create_dataset.py

sonar.test.inclusions=\
api/tests/**/*.py