sonar.projectKey=ipsita-17_enterprise-ai-aks-inference-platform
sonar.organization=ipsita-17

sonar.sources=api/app,model/training
sonar.tests=api/tests

sonar.python.version=3.12

sonar.exclusions=**/__pycache__/**,**/*.pyc,model/artifacts/**