sonar.projectKey=ipsita-17_enterprise-ai-aks-inference-platform
sonar.organization=ipsita-patra

sonar.sources=.

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/__pycache__/**

sonar.coverage.exclusions=\
model/training/train.py,\
model/training/mlflow_config.py