apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-inference-api

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: ai-inference-api

  template:
    metadata:
      labels:
        app: ai-inference-api

    spec:
      containers:
      - name: ai-inference-api

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.service.targetPort }}

        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}

          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}