apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-inference-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: ai-inference-api

  template:
    metadata:
      labels:
        app: ai-inference-api

    spec:
      containers:
      - name: ai-inference-api
        image: ipsitaacr.azurecr.io/ai-inference-api:latest

        ports:
        - containerPort: 8000