apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: ai-api-monitor

spec:
  selector:
    matchLabels:
      app: ai-api

  endpoints:
    - port: http
      path: /metrics
      interval: 15s