name: AI Inference CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install -r model/training/requirements.txt
          pip install pytest pytest-cov

      - name: Run Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest api/tests \
            --cov=api/app \
            --cov-report=xml:coverage.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  sonar:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  train:
    needs: sonar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Dependencies
        run: |
          pip install -r model/training/requirements.txt

      - name: Train Model
        run: |
          python model/training/train.py

      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: mlruns/
          if-no-files-found: warn

  trivy:
    needs: train
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .

  docker:
    needs: trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build -t ipsuuu/ai-inference-api:${{ github.sha }} .
          docker tag ipsuuu/ai-inference-api:${{ github.sha }} ipsuuu/ai-inference-api:latest

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ipsuuu/ai-inference-api:${{ github.sha }}

      - name: Push Image
        run: |
          docker push ipsuuu/ai-inference-api:${{ github.sha }}
          docker push ipsuuu/ai-inference-api:latest